using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace myFirstWebApi.App_Code.Controllers
{
    public class ProductController : ApiController
    {
        #region array
        Product[] products = new Product[]
        {
                new Product { Id =1, Name = "Amaranth", ScientificName = "Amaranthus cruentus", Category = "Veg", Price = 988, Quantity = 100},
                new Product { Id =2, Name = "Arugula", ScientificName = "Eruca sativa", Category = "Veg", Price = 349, Quantity = 87},
                new Product { Id =3, Name = "Beet greens", ScientificName = "Beta vulgaris vulgaris", Category = "Veg", Price = 545, Quantity = 12},
                new Product { Id =4, Name = "Bok choy", ScientificName = "Brassica rapa (chinensis)", Category = "Veg", Price = 323, Quantity = 15},
                new Product { Id =5, Name = "Borage greens", ScientificName = "Borago officinalis", Category = "Veg", Price = 666, Quantity = 87},
                new Product { Id =6, Name = "Broccolini", ScientificName = "Brassica oleracea", Category = "Veg", Price = 513, Quantity = 54},
                new Product { Id =7, Name = "Brussels sprouts", ScientificName = "Brassica oleracea (gemmifera)", Category = "Veg", Price = 727, Quantity = 85},
                new Product { Id =8, Name = "Cabbage", ScientificName = "Brassica oleracea (capitata)", Category = "Veg", Price = 546, Quantity = 81},
                new Product { Id =9, Name = "Catsear", ScientificName = "Hypochaeris radicata", Category = "Veg", Price = 215, Quantity = 65},
                new Product { Id =10, Name = "Celery", ScientificName = "Apium graveolens", Category = "Veg", Price = 450, Quantity = 36},
                new Product { Id =11, Name = "Celtuce", ScientificName = "Lactuca sativa (asparagina)", Category = "Veg", Price = 48, Quantity = 89},
                new Product { Id =12, Name = "Chaya", ScientificName = "Cnidoscolus aconitifolius aconitifolius", Category = "Veg", Price = 756, Quantity = 20},
                new Product { Id =13, Name = "Chickweed", ScientificName = "Stellaria", Category = "Veg", Price = 218, Quantity = 93},
                new Product { Id =14, Name = "Chicory", ScientificName = "Cichorium intybus", Category = "Veg", Price = 158, Quantity = 14},
                new Product { Id =15, Name = "Chinese mallow", ScientificName = "Malva verticillata", Category = "Veg", Price = 752, Quantity = 22},
                new Product { Id =16, Name = "Chrysanthemum (leaves)", ScientificName = "Chrysanthemum coronarium", Category = "Veg", Price = 1000, Quantity = 35},
                new Product { Id =17, Name = "Collard greens", ScientificName = "Brassica oleracea", Category = "Veg", Price = 388, Quantity = 30},
                new Product { Id =18, Name = "Common purslane", ScientificName = "Portulaca oleracea", Category = "Veg", Price = 438, Quantity = 85},
                new Product { Id =19, Name = "Corn salad", ScientificName = "Valerianella locusta", Category = "Veg", Price = 684, Quantity = 45},
                new Product { Id =20, Name = "Cress", ScientificName = "Lepidium sativum", Category = "Veg", Price = 350, Quantity = 30},
                new Product { Id =21, Name = "Dandelion", ScientificName = "Taraxacum officinale", Category = "Veg", Price = 405, Quantity = 95},
                new Product { Id =22, Name = "Dill", ScientificName = "Anethum graveolens", Category = "Veg", Price = 902, Quantity = 21},
                new Product { Id =23, Name = "Endive", ScientificName = "Cichorium endivia", Category = "Veg", Price = 236, Quantity = 78},
                new Product { Id =24, Name = "Fat hen", ScientificName = "Chenopodium album", Category = "Veg", Price = 403, Quantity = 58},
                new Product { Id =25, Name = "Fiddlehead", ScientificName = "Pteridium aquilinum", Category = "Veg", Price = 823, Quantity = 85},
                new Product { Id =26, Name = "Athyrium esculentum", ScientificName = "", Category = "Veg", Price = 933, Quantity = 47},
                new Product { Id =27, Name = "Fluted pumpkin", ScientificName = "Telfairia occidentalis", Category = "Veg", Price = 714, Quantity = 54},
                new Product { Id =28, Name = "Garden rocket", ScientificName = "Eruca sativa", Category = "Veg", Price = 322, Quantity = 58},
                new Product { Id =29, Name = "Golden samphire", ScientificName = "Inula crithmoides", Category = "Veg", Price = 801, Quantity = 94},
                new Product { Id =30, Name = "Good King Henry", ScientificName = "Chenopodium bonus-henricus", Category = "Veg", Price = 189, Quantity = 13},
                new Product { Id =31, Name = "Grape (leaves)", ScientificName = "Vitis", Category = "Veg", Price = 239, Quantity = 30},
                new Product { Id =32, Name = "Greater plantain", ScientificName = "Plantago major", Category = "Veg", Price = 298, Quantity = 73},
                new Product { Id =33, Name = "Kai-lan", ScientificName = "Brassica rapa (alboglabra)", Category = "Veg", Price = 786, Quantity = 85},
                new Product { Id =34, Name = "Kale", ScientificName = "Brassica oleracea (acephala)", Category = "Veg", Price = 661, Quantity = 37},
                new Product { Id =35, Name = "Komatsuna", ScientificName = "Brassica rapa (pervidis / komatsuna)", Category = "Veg", Price = 774, Quantity = 22},
                new Product { Id =36, Name = "Kuka", ScientificName = "Adansonia", Category = "Veg", Price = 19, Quantity = 80},
                new Product { Id =37, Name = "Lagos bologi", ScientificName = "Talinum fruticosum", Category = "Veg", Price = 257, Quantity = 90},
                new Product { Id =38, Name = "Lamb's lettuce", ScientificName = "Valerianella locusta", Category = "Veg", Price = 593, Quantity = 94},
                new Product { Id =39, Name = "Lamb's quarters", ScientificName = "Chenopodium album", Category = "Veg", Price = 199, Quantity = 57},
                new Product { Id =40, Name = "Land cress", ScientificName = "Barbarea verna", Category = "Veg", Price = 817, Quantity = 67},
                new Product { Id =41, Name = "Lettuce", ScientificName = "Lactuca sativa", Category = "Veg", Price = 538, Quantity = 52},
                new Product { Id =42, Name = "Lizard's tail", ScientificName = "Houttuynia cordata", Category = "Veg", Price = 774, Quantity = 59},
                new Product { Id =43, Name = "Malabar spinach", ScientificName = "Basella alba", Category = "Veg", Price = 808, Quantity = 24},
                new Product { Id =44, Name = "Melokhia", ScientificName = "Corchorus olitorius", Category = "Veg", Price = 371, Quantity = 65},
                new Product { Id =45, Name = "Corchorus capsularis", ScientificName = "", Category = "Veg", Price = 508, Quantity = 48},
                new Product { Id =46, Name = "Miner's lettuce (Winter purslane)", ScientificName = "Claytonia perfoliata", Category = "Veg", Price = 670, Quantity = 16},
                new Product { Id =47, Name = "Mizuna greens", ScientificName = "Brassica rapa (nipposinica)", Category = "Veg", Price = 406, Quantity = 65},
                new Product { Id =48, Name = "Mustard", ScientificName = "Sinapis alba", Category = "Veg", Price = 883, Quantity = 66},
                new Product { Id =49, Name = "Napa cabbage", ScientificName = "Brassica rapa (pekinensis)", Category = "Veg", Price = 142, Quantity = 12},
                new Product { Id =50, Name = "New Zealand Spinach", ScientificName = "Tetragonia tetragonioides", Category = "Veg", Price = 341, Quantity = 16},
                new Product { Id =51, Name = "Orache", ScientificName = "Atriplex hortensis", Category = "Veg", Price = 681, Quantity = 91},
                new Product { Id =52, Name = "Pak choy ", ScientificName = "Brassica rapa (chinensis)", Category = "Veg", Price = 27, Quantity = 58},
                new Product { Id =53, Name = "Paracress", ScientificName = "Acmella oleracea", Category = "Veg", Price = 231, Quantity = 61},
                new Product { Id =54, Name = "Pea sprouts / leaves", ScientificName = "Pisum sativum", Category = "Veg", Price = 967, Quantity = 59},
                new Product { Id =55, Name = "Poke", ScientificName = "Phytolacca americana", Category = "Veg", Price = 612, Quantity = 41},
                new Product { Id =56, Name = "Radicchio", ScientificName = "Cichorium intybus", Category = "Veg", Price = 951, Quantity = 20},
                new Product { Id =57, Name = "Rapini (broccoli rabe)", ScientificName = "Brassica rapa rapa", Category = "Veg", Price = 343, Quantity = 58},
                new Product { Id =58, Name = "Samphire", ScientificName = "Crithmum maritimum", Category = "Veg", Price = 973, Quantity = 37},
                new Product { Id =59, Name = "Sculpit / Stridolo", ScientificName = "Silene inflata", Category = "Veg", Price = 727, Quantity = 80},
                new Product { Id =60, Name = "Sea beet", ScientificName = "Beta vulgaris maritima", Category = "Veg", Price = 57, Quantity = 65},
                new Product { Id =61, Name = "Sea kale", ScientificName = "Crambe maritima", Category = "Veg", Price = 166, Quantity = 29},
                new Product { Id =62, Name = "Sierra Leone bologi", ScientificName = "Crassocephalum", Category = "Veg", Price = 607, Quantity = 17},
                new Product { Id =63, Name = "Soko", ScientificName = "Celosia argentea", Category = "Veg", Price = 704, Quantity = 66},
                new Product { Id =64, Name = "Sorrel", ScientificName = "Rumex acetosa", Category = "Veg", Price = 462, Quantity = 83},
                new Product { Id =65, Name = "Sour cabbage", ScientificName = "Brassica oleracea", Category = "Veg", Price = 452, Quantity = 27},
                new Product { Id =66, Name = "Spinach", ScientificName = "Spinacia oleracea", Category = "Veg", Price = 912, Quantity = 94},
                new Product { Id =67, Name = "Summer purslane", ScientificName = "Portulaca oleracea", Category = "Veg", Price = 105, Quantity = 80},
                new Product { Id =68, Name = "Swiss chard", ScientificName = "Beta vulgaris cicla (flavescens)", Category = "Veg", Price = 262, Quantity = 32},
                new Product { Id =69, Name = "Tatsoi", ScientificName = "Brassica rapa (rosularis)", Category = "Veg", Price = 18, Quantity = 50},
                new Product { Id =70, Name = "Turnip greens", ScientificName = "Brassica rapa (rapifera)", Category = "Veg", Price = 217, Quantity = 10},
                new Product { Id =71, Name = "Watercress", ScientificName = "Nasturtium officinale", Category = "Veg", Price = 508, Quantity = 57},
                new Product { Id =72, Name = "Water spinach", ScientificName = "Ipomoea aquatica", Category = "Veg", Price = 548, Quantity = 58},
                new Product { Id =73, Name = "Wheatgrass", ScientificName = "Triticum aestivum", Category = "Veg", Price = 962, Quantity = 45},
                new Product { Id =74, Name = "Yarrow", ScientificName = "Achillea millefolium", Category = "Veg", Price = 718, Quantity = 76},
                new Product { Id =75, Name = "Yao choy", ScientificName = "Brassica napus", Category = "Veg", Price = 522, Quantity = 15},
                new Product { Id =76, Name = "Pumpkins", ScientificName = "", Category = "Veg", Price = 598, Quantity = 60},
                new Product { Id =77, Name = "Avocado", ScientificName = "Persea americana", Category = "Veg", Price = 838, Quantity = 67},
                new Product { Id =78, Name = "Bell pepper", ScientificName = "Capsicum annuum", Category = "Veg", Price = 788, Quantity = 68},
                new Product { Id =79, Name = "Bitter melon", ScientificName = "", Category = "Veg", Price = 198, Quantity = 100},
                new Product { Id =80, Name = "Bitter gourd", ScientificName = "Momordica charantia", Category = "Veg", Price = 366, Quantity = 44},
                new Product { Id =81, Name = "Chayote", ScientificName = "Sechium edule", Category = "Veg", Price = 249, Quantity = 18},
                new Product { Id =82, Name = "Cucumber", ScientificName = "Cucumis sativus", Category = "Veg", Price = 252, Quantity = 27},
                new Product { Id =83, Name = "Ivy gourd", ScientificName = "Coccinia grandis", Category = "Veg", Price = 585, Quantity = 61},
                new Product { Id =84, Name = "Eggplant / Aubergine / Brinjal", ScientificName = "Solanum melongena", Category = "Veg", Price = 416, Quantity = 94},
                new Product { Id =85, Name = "Luffa", ScientificName = "Luffa cylindrica", Category = "Veg", Price = 423, Quantity = 72},
                new Product { Id =86, Name = "Olive fruit", ScientificName = "Olea europaea", Category = "Veg", Price = 154, Quantity = 56},
                new Product { Id =87, Name = "Pumpkin", ScientificName = "Cucurbita", Category = "Veg", Price = 818, Quantity = 88},
                new Product { Id =88, Name = "Squash", ScientificName = "Cucurbita", Category = "Veg", Price = 631, Quantity = 21},
                new Product { Id =89, Name = "Sweet pepper", ScientificName = "Capsicum annuum (grossum)", Category = "Veg", Price = 945, Quantity = 34},
                new Product { Id =90, Name = "Tinda", ScientificName = "Praecitrullus fistulosus", Category = "Veg", Price = 411, Quantity = 48},
                new Product { Id =91, Name = "Tomatillo", ScientificName = "Physalis philadelphica", Category = "Veg", Price = 384, Quantity = 84},
                new Product { Id =92, Name = "Tomato", ScientificName = "Solanum lycopersicum", Category = "Veg", Price = 760, Quantity = 33},
                new Product { Id =93, Name = "Vanilla", ScientificName = "Vanilla", Category = "Veg", Price = 441, Quantity = 91},
                new Product { Id =94, Name = "West Indian gherkin", ScientificName = "Cucumis anguria", Category = "Veg", Price = 233, Quantity = 30},
                new Product { Id =95, Name = "Winter melon", ScientificName = "Benincasa hispida", Category = "Veg", Price = 594, Quantity = 36},
                new Product { Id =96, Name = "Zucchini / Courgette / Marrow", ScientificName = "Cucurbita pepo", Category = "Veg", Price = 877, Quantity = 70},
                new Product { Id =97, Name = "Artichoke", ScientificName = "Cynara cardunculus / scolymus", Category = "Veg", Price = 806, Quantity = 18},
                new Product { Id =98, Name = "Broccoli", ScientificName = "Brassica oleracea", Category = "Veg", Price = 24, Quantity = 60},
                new Product { Id =99, Name = "Broccolini flowers", ScientificName = "Brassica oleracea", Category = "Veg", Price = 144, Quantity = 95},
                new Product { Id =100, Name = "Caper", ScientificName = "Capparis spinosa", Category = "Veg", Price = 28, Quantity = 37},
                new Product { Id =101, Name = "Cauliflower", ScientificName = "Brassica oleracea", Category = "Veg", Price = 420, Quantity = 33},
                new Product { Id =102, Name = "Daylily[2]", ScientificName = "Hemerocallis fulva", Category = "Veg", Price = 176, Quantity = 17},
                new Product { Id =103, Name = "Courgette flowers", ScientificName = "Cucurbita", Category = "Veg", Price = 814, Quantity = 58},
                new Product { Id =104, Name = "Squash blossoms", ScientificName = "Cucurbita", Category = "Veg", Price = 686, Quantity = 78},
                new Product { Id =105, Name = "American groundnut", ScientificName = "Apios americana", Category = "Veg", Price = 290, Quantity = 76},
                new Product { Id =106, Name = "Azuki bean", ScientificName = "Vigna angularis", Category = "Veg", Price = 173, Quantity = 77},
                new Product { Id =107, Name = "Black-eyed pea", ScientificName = "Vigna unguiculata unguiculata", Category = "Veg", Price = 584, Quantity = 62},
                new Product { Id =108, Name = "Chickpea", ScientificName = "Cicer arietinum", Category = "Veg", Price = 762, Quantity = 49},
                new Product { Id =109, Name = "Common bean", ScientificName = "Phaseolus vulgaris", Category = "Veg", Price = 863, Quantity = 29},
                new Product { Id =110, Name = "Drumstick", ScientificName = "Moringa oleifera", Category = "Veg", Price = 254, Quantity = 36},
                new Product { Id =111, Name = "Dolichos bean", ScientificName = "Lablab purpureus", Category = "Veg", Price = 145, Quantity = 14},
                new Product { Id =112, Name = "Fava bean", ScientificName = "Vicia faba", Category = "Veg", Price = 42, Quantity = 27},
                new Product { Id =113, Name = "Garbanzo", ScientificName = "Cicer arietinum", Category = "Veg", Price = 319, Quantity = 100},
                new Product { Id =114, Name = "Green bean (French bean)", ScientificName = "Phaseolus vulgaris", Category = "Veg", Price = 141, Quantity = 50},
                new Product { Id =115, Name = "Guar", ScientificName = "Cyamopsis tetragonoloba", Category = "Veg", Price = 749, Quantity = 98},
                new Product { Id =116, Name = "Horse gram", ScientificName = "Macrotyloma uniflorum", Category = "Veg", Price = 613, Quantity = 97},
                new Product { Id =117, Name = "Indian pea", ScientificName = "Lathyrus sativus", Category = "Veg", Price = 191, Quantity = 25},
                new Product { Id =118, Name = "Lentil", ScientificName = "Lens culinaris", Category = "Veg", Price = 29, Quantity = 52},
                new Product { Id =119, Name = "Lima bean", ScientificName = "Phaseolus lunatus", Category = "Veg", Price = 840, Quantity = 40},
                new Product { Id =120, Name = "Moth bean", ScientificName = "Vigna acontifolia", Category = "Veg", Price = 649, Quantity = 11},
                new Product { Id =121, Name = "Mung bean", ScientificName = "Vigna radiata", Category = "Veg", Price = 98, Quantity = 56},
                new Product { Id =122, Name = "Okra", ScientificName = "Abelmoschus esculentus", Category = "Veg", Price = 595, Quantity = 67},
                new Product { Id =123, Name = "Pea", ScientificName = "Pisum sativum", Category = "Veg", Price = 174, Quantity = 41},
                new Product { Id =124, Name = "Peanut", ScientificName = "Arachis hypogaea", Category = "Veg", Price = 652, Quantity = 68},
                new Product { Id =125, Name = "Pigeon pea", ScientificName = "Cajanus cajan", Category = "Veg", Price = 711, Quantity = 80},
                new Product { Id =126, Name = "Ricebean", ScientificName = "Vigna umbellata", Category = "Veg", Price = 372, Quantity = 29},
                new Product { Id =127, Name = "Runner bean", ScientificName = "Phaseolus coccineus", Category = "Veg", Price = 413, Quantity = 25},
                new Product { Id =128, Name = "Snap pea (sugarsnap, mangetout)", ScientificName = "Pisum sativum (macrocarpon)", Category = "Veg", Price = 346, Quantity = 32},
                new Product { Id =129, Name = "Snow pea (mangetout)", ScientificName = "Pisum sativum (saccharatum)", Category = "Veg", Price = 177, Quantity = 38},
                new Product { Id =130, Name = "Soybean", ScientificName = "Glycine max", Category = "Veg", Price = 11, Quantity = 33},
                new Product { Id =131, Name = "Tarwi (Tarhui / Chocho)", ScientificName = "Lupinus mutabilis", Category = "Veg", Price = 764, Quantity = 76},
                new Product { Id =132, Name = "Tepary bean", ScientificName = "Phaseolus acutifolius", Category = "Veg", Price = 257, Quantity = 19},
                new Product { Id =133, Name = "Urad bean", ScientificName = "Vigna mungo", Category = "Veg", Price = 465, Quantity = 83},
                new Product { Id =134, Name = "Velvet bean", ScientificName = "Mucuna pruriens", Category = "Veg", Price = 618, Quantity = 79},
                new Product { Id =135, Name = "Winged bean", ScientificName = "Psophocarpus tetragonolobus", Category = "Veg", Price = 979, Quantity = 26},
                new Product { Id =136, Name = "Yardlong bean", ScientificName = "Vigna unguiculata (sesquipedalis)", Category = "Veg", Price = 356, Quantity = 30},
                new Product { Id =137, Name = "Asparagus", ScientificName = "Asparagus officinalis", Category = "Veg", Price = 530, Quantity = 20},
                new Product { Id =138, Name = "Cardoon", ScientificName = "Cynara cardunculus", Category = "Veg", Price = 699, Quantity = 83},
                new Product { Id =139, Name = "Celeriac", ScientificName = "Apium graveolens (rapaceum)", Category = "Veg", Price = 269, Quantity = 52},
                new Product { Id =140, Name = "Celery", ScientificName = "Apium graveolens", Category = "Veg", Price = 777, Quantity = 94},
                new Product { Id =141, Name = "Chives", ScientificName = "Allium schoenoprasum", Category = "Veg", Price = 554, Quantity = 39},
                new Product { Id =142, Name = "Elephant garlic", ScientificName = "Allium ampeloprasum (ampeloprasum)", Category = "Veg", Price = 998, Quantity = 79},
                new Product { Id =143, Name = "Florence fennel", ScientificName = "Foeniculum vulgare (dulce)", Category = "Veg", Price = 553, Quantity = 57},
                new Product { Id =144, Name = "Garlic", ScientificName = "Allium sativum", Category = "Veg", Price = 430, Quantity = 53},
                new Product { Id =145, Name = "Garlic chives", ScientificName = "Allium tuberosum", Category = "Veg", Price = 907, Quantity = 66},
                new Product { Id =146, Name = "Kohlrabi", ScientificName = "Brassica oleracea (gongylodes)", Category = "Veg", Price = 748, Quantity = 64},
                new Product { Id =147, Name = "Kurrat", ScientificName = "Allium ampeloprasum (kurrat)", Category = "Veg", Price = 410, Quantity = 55},
                new Product { Id =148, Name = "Lemongrass", ScientificName = "Cymbopogon citratus", Category = "Veg", Price = 98, Quantity = 63},
                new Product { Id =149, Name = "Leek", ScientificName = "Allium porrum", Category = "Veg", Price = 620, Quantity = 81},
                new Product { Id =150, Name = "Lotus root", ScientificName = "Nelumbo nucifera", Category = "Veg", Price = 809, Quantity = 68},
                new Product { Id =151, Name = "Nopal", ScientificName = "Opuntia ficus-indica", Category = "Veg", Price = 933, Quantity = 44},
                new Product { Id =152, Name = "Onion", ScientificName = "Allium cepa", Category = "Veg", Price = 220, Quantity = 57},
                new Product { Id =153, Name = "Pearl onion", ScientificName = "Allium ampeloprasum (sectivum)", Category = "Veg", Price = 746, Quantity = 49},
                new Product { Id =154, Name = "Potato onion", ScientificName = "Allium cepa (aggregatum)", Category = "Veg", Price = 93, Quantity = 66},
                new Product { Id =155, Name = "Prussian asparagus", ScientificName = "Ornithogalum pyrenaicum", Category = "Veg", Price = 171, Quantity = 36},
                new Product { Id =156, Name = "Spring onion / Scallion", ScientificName = "Allium wakegi", Category = "Veg", Price = 302, Quantity = 50},
                new Product { Id =157, Name = "Shallot", ScientificName = "Allium cepa (aggregatum)", Category = "Veg", Price = 982, Quantity = 82},
                new Product { Id =158, Name = "Tree onion[3]", ScientificName = "Allium × proliferum", Category = "Veg", Price = 756, Quantity = 85},
                new Product { Id =159, Name = "Welsh onion", ScientificName = "Allium fistulosum", Category = "Veg", Price = 632, Quantity = 86},
                new Product { Id =160, Name = "Wild leek", ScientificName = "Allium tricoccum", Category = "Veg", Price = 820, Quantity = 83},
                new Product { Id =161, Name = "Ahipa", ScientificName = "Pachyrhizus ahipa", Category = "Veg", Price = 78, Quantity = 21},
                new Product { Id =162, Name = "Arracacha", ScientificName = "Arracacia xanthorrhiza", Category = "Veg", Price = 1000, Quantity = 83},
                new Product { Id =163, Name = "Bamboo shoot", ScientificName = "Bambusa vulgaris", Category = "Veg", Price = 591, Quantity = 53},
                new Product { Id =164, Name = "Phyllostachys edulis", ScientificName = "", Category = "Veg", Price = 705, Quantity = 56},
                new Product { Id =165, Name = "Beetroot", ScientificName = "Beta vulgaris vulgaris", Category = "Veg", Price = 630, Quantity = 46},
                new Product { Id =166, Name = "Burdock", ScientificName = "Arctium lappa", Category = "Veg", Price = 984, Quantity = 30},
                new Product { Id =167, Name = "Broadleaf arrowhead", ScientificName = "Sagittaria latifolia", Category = "Veg", Price = 428, Quantity = 43},
                new Product { Id =168, Name = "Camas", ScientificName = "Camassia", Category = "Veg", Price = 951, Quantity = 88},
                new Product { Id =169, Name = "Canna", ScientificName = "Canna", Category = "Veg", Price = 915, Quantity = 100},
                new Product { Id =170, Name = "Carrot", ScientificName = "Daucus carota", Category = "Veg", Price = 741, Quantity = 35},
                new Product { Id =171, Name = "Cassava", ScientificName = "Manihot esculenta", Category = "Veg", Price = 731, Quantity = 69},
                new Product { Id =172, Name = "Chinese artichoke", ScientificName = "Stachys affinis", Category = "Veg", Price = 239, Quantity = 52},
                new Product { Id =173, Name = "Daikon", ScientificName = "Raphanus sativus (longipinnatus)", Category = "Veg", Price = 525, Quantity = 87},
                new Product { Id =174, Name = "Earthnut pea", ScientificName = "Lathyrus tuberosus", Category = "Veg", Price = 246, Quantity = 30},
                new Product { Id =175, Name = "Elephant foot yam", ScientificName = "Amorphophallus paeoniifolius", Category = "Veg", Price = 753, Quantity = 51},
                new Product { Id =176, Name = "Ensete", ScientificName = "Ensete ventricosum", Category = "Veg", Price = 942, Quantity = 52},
                new Product { Id =177, Name = "Galangal", ScientificName = "Alpinia galanga", Category = "Veg", Price = 370, Quantity = 81},
                new Product { Id =178, Name = "Ginger", ScientificName = "Zingiber officinale", Category = "Veg", Price = 805, Quantity = 50},
                new Product { Id =179, Name = "Hamburg parsley", ScientificName = "Petroselinum crispum tuberosum", Category = "Veg", Price = 467, Quantity = 67},
                new Product { Id =180, Name = "Horseradish", ScientificName = "Armoracia rusticana", Category = "Veg", Price = 491, Quantity = 58},
                new Product { Id =181, Name = "Jerusalem artichoke", ScientificName = "Helianthus tuberosus", Category = "Veg", Price = 446, Quantity = 94},
                new Product { Id =182, Name = "Jícama", ScientificName = "Pachyrhizus erosus", Category = "Veg", Price = 688, Quantity = 76},
                new Product { Id =183, Name = "Mashua", ScientificName = "Tropaeolum tuberosum", Category = "Veg", Price = 218, Quantity = 76},
                new Product { Id =184, Name = "Parsnip", ScientificName = "Pastinaca sativa", Category = "Veg", Price = 406, Quantity = 15},
                new Product { Id =185, Name = "Pignut", ScientificName = "Conopodium majus", Category = "Veg", Price = 692, Quantity = 32},
                new Product { Id =186, Name = "Potato", ScientificName = "Solanum tuberosum", Category = "Veg", Price = 635, Quantity = 47},
                new Product { Id =187, Name = "Prairie turnip", ScientificName = "Psoralea esculenta", Category = "Veg", Price = 743, Quantity = 44},
                new Product { Id =188, Name = "Radish", ScientificName = "Raphanus sativus", Category = "Veg", Price = 621, Quantity = 57},
                new Product { Id =189, Name = "Rutabaga", ScientificName = "Brassica napus (napobrassica)", Category = "Veg", Price = 951, Quantity = 19},
                new Product { Id =190, Name = "Salsify", ScientificName = "Tragopogon porrifolius", Category = "Veg", Price = 142, Quantity = 67},
                new Product { Id =191, Name = "Scorzonera", ScientificName = "Scorzonera hispanica", Category = "Veg", Price = 660, Quantity = 52},
                new Product { Id =192, Name = "Skirret", ScientificName = "Sium sisarum", Category = "Veg", Price = 669, Quantity = 95},
                new Product { Id =193, Name = "Swede", ScientificName = "Brassica napus (napobrassica)", Category = "Veg", Price = 533, Quantity = 83},
                new Product { Id =194, Name = "Sweet potato (Kumara)", ScientificName = "Ipomoea batatas", Category = "Veg", Price = 319, Quantity = 19},
                new Product { Id =195, Name = "Taro", ScientificName = "Colocasia esculenta", Category = "Veg", Price = 131, Quantity = 18},
                new Product { Id =196, Name = "Ti", ScientificName = "Cordyline fruticosa", Category = "Veg", Price = 355, Quantity = 24},
                new Product { Id =197, Name = "Tigernut", ScientificName = "Cyperus esculentus", Category = "Veg", Price = 292, Quantity = 39},
                new Product { Id =198, Name = "Turmeric", ScientificName = "Curcuma longa", Category = "Veg", Price = 935, Quantity = 38},
                new Product { Id =199, Name = "Turnip", ScientificName = "Brassica rapa (rapifera)", Category = "Veg", Price = 16, Quantity = 82},
                new Product { Id =200, Name = "Ulluco", ScientificName = "Ullucus tuberosus", Category = "Veg", Price = 232, Quantity = 44},
                new Product { Id =201, Name = "Wasabi", ScientificName = "Wasabia japonica", Category = "Veg", Price = 48, Quantity = 37},
                new Product { Id =202, Name = "Water caltrop", ScientificName = "Trapa natans", Category = "Veg", Price = 817, Quantity = 14},
                new Product { Id =203, Name = "Trapa bicornis", ScientificName = "", Category = "Veg", Price = 90, Quantity = 45},
                new Product { Id =204, Name = "Water chestnut", ScientificName = "Eleocharis dulcis", Category = "Veg", Price = 609, Quantity = 32},
                new Product { Id =205, Name = "Yacón", ScientificName = "Smallanthus sonchifolius", Category = "Veg", Price = 569, Quantity = 25},
                new Product { Id =206, Name = "Yam", ScientificName = "Dioscorea [4]", Category = "Veg", Price = 182, Quantity = 42},
                new Product { Id =207, Name = "Arame", ScientificName = "Eisenia bicyclis", Category = "Veg", Price = 134, Quantity = 21},
                new Product { Id =208, Name = "Carola", ScientificName = "Callophyllis variegata", Category = "Veg", Price = 597, Quantity = 47},
                new Product { Id =209, Name = "Dabberlocks (Badderlocks)", ScientificName = "Alaria esculenta", Category = "Veg", Price = 191, Quantity = 18},
                new Product { Id =210, Name = "Dulse (Dillisk)", ScientificName = "Palmaria palmata", Category = "Veg", Price = 902, Quantity = 67},
                new Product { Id =211, Name = "Hijiki", ScientificName = "Hizikia fusiformis", Category = "Veg", Price = 503, Quantity = 88},
                new Product { Id =212, Name = "Kombu", ScientificName = "Laminaria japonica", Category = "Veg", Price = 892, Quantity = 83},
                new Product { Id =213, Name = "Laver / Gim", ScientificName = "Porphyra", Category = "Veg", Price = 707, Quantity = 89},
                new Product { Id =214, Name = "Mozuku", ScientificName = "Cladosiphon okamuranus", Category = "Veg", Price = 797, Quantity = 16},
                new Product { Id =215, Name = "Nori", ScientificName = "Porphyra", Category = "Veg", Price = 406, Quantity = 75},
                new Product { Id =216, Name = "Ogonori", ScientificName = "Gracilaria", Category = "Veg", Price = 960, Quantity = 12},
                new Product { Id =217, Name = "Sea grape", ScientificName = "Caulerpa", Category = "Veg", Price = 232, Quantity = 48},
                new Product { Id =218, Name = "Sea lettuce", ScientificName = "Ulva lactuca", Category = "Veg", Price = 283, Quantity = 43},
                new Product { Id =219, Name = "Wakame", ScientificName = "Undaria pinnatifida", Category = "Veg", Price = 917, Quantity = 42},
                new Product { Id =220, Name = "Apple", ScientificName = "Apple", Category = "Fru", Price = 54, Quantity = 83},
                new Product { Id =221, Name = "Apricot", ScientificName = "Apricot", Category = "Fru", Price = 304, Quantity = 65},
                new Product { Id =222, Name = "Avocado", ScientificName = "Avocado", Category = "Fru", Price = 666, Quantity = 92},
                new Product { Id =223, Name = "Banana", ScientificName = "Banana", Category = "Fru", Price = 821, Quantity = 53},
                new Product { Id =224, Name = "Bilberry", ScientificName = "Bilberry", Category = "Fru", Price = 830, Quantity = 65},
                new Product { Id =225, Name = "Blackberry", ScientificName = "Blackberry", Category = "Fru", Price = 334, Quantity = 52},
                new Product { Id =226, Name = "Blackcurrant", ScientificName = "Blackcurrant", Category = "Fru", Price = 410, Quantity = 90},
                new Product { Id =227, Name = "Blueberry", ScientificName = "Blueberry", Category = "Fru", Price = 855, Quantity = 45},
                new Product { Id =228, Name = "Boysenberry", ScientificName = "Boysenberry", Category = "Fru", Price = 54, Quantity = 14},
                new Product { Id =229, Name = "Currant", ScientificName = "Currant", Category = "Fru", Price = 340, Quantity = 28},
                new Product { Id =230, Name = "Cherry", ScientificName = "Cherry", Category = "Fru", Price = 894, Quantity = 62},
                new Product { Id =231, Name = "Cherimoya", ScientificName = "Cherimoya", Category = "Fru", Price = 845, Quantity = 37},
                new Product { Id =232, Name = "Cloudberry", ScientificName = "Cloudberry", Category = "Fru", Price = 466, Quantity = 52},
                new Product { Id =233, Name = "Coconut", ScientificName = "Coconut", Category = "Fru", Price = 676, Quantity = 66},
                new Product { Id =234, Name = "Cranberry", ScientificName = "Cranberry", Category = "Fru", Price = 751, Quantity = 51},
                new Product { Id =235, Name = "Damson", ScientificName = "Damson", Category = "Fru", Price = 553, Quantity = 89},
                new Product { Id =236, Name = "Date", ScientificName = "Date", Category = "Fru", Price = 610, Quantity = 56},
                new Product { Id =237, Name = "Dragonfruit", ScientificName = "Dragonfruit", Category = "Fru", Price = 777, Quantity = 52},
                new Product { Id =238, Name = "Durian", ScientificName = "Durian", Category = "Fru", Price = 840, Quantity = 19},
                new Product { Id =239, Name = "Elderberry", ScientificName = "Elderberry", Category = "Fru", Price = 246, Quantity = 100},
                new Product { Id =240, Name = "Feijoa", ScientificName = "Feijoa", Category = "Fru", Price = 549, Quantity = 83},
                new Product { Id =241, Name = "Fig", ScientificName = "Fig", Category = "Fru", Price = 156, Quantity = 68},
                new Product { Id =242, Name = "Goji berry", ScientificName = "Goji berry", Category = "Fru", Price = 989, Quantity = 96},
                new Product { Id =243, Name = "Gooseberry", ScientificName = "Gooseberry", Category = "Fru", Price = 537, Quantity = 38},
                new Product { Id =244, Name = "Grape", ScientificName = "Grape", Category = "Fru", Price = 765, Quantity = 23},
                new Product { Id =245, Name = "Raisin", ScientificName = "Raisin", Category = "Fru", Price = 221, Quantity = 69},
                new Product { Id =246, Name = "Grapefruit", ScientificName = "Grapefruit", Category = "Fru", Price = 170, Quantity = 31},
                new Product { Id =247, Name = "Guava", ScientificName = "Guava", Category = "Fru", Price = 178, Quantity = 14},
                new Product { Id =248, Name = "Huckleberry", ScientificName = "Huckleberry", Category = "Fru", Price = 997, Quantity = 16},
                new Product { Id =249, Name = "Jabuticaba", ScientificName = "Jabuticaba", Category = "Fru", Price = 976, Quantity = 96},
                new Product { Id =250, Name = "Jackfruit", ScientificName = "Jackfruit", Category = "Fru", Price = 821, Quantity = 25},
                new Product { Id =251, Name = "Jambul", ScientificName = "Jambul", Category = "Fru", Price = 97, Quantity = 73},
                new Product { Id =252, Name = "Jujube", ScientificName = "Jujube", Category = "Fru", Price = 862, Quantity = 13},
                new Product { Id =253, Name = "Juniper berry", ScientificName = "Juniper berry", Category = "Fru", Price = 388, Quantity = 12},
                new Product { Id =254, Name = "Kiwifruit", ScientificName = "Kiwifruit", Category = "Fru", Price = 801, Quantity = 91},
                new Product { Id =255, Name = "Kumquat", ScientificName = "Kumquat", Category = "Fru", Price = 311, Quantity = 39},
                new Product { Id =256, Name = "Lemon", ScientificName = "Lemon", Category = "Fru", Price = 872, Quantity = 15},
                new Product { Id =257, Name = "Lime", ScientificName = "Lime", Category = "Fru", Price = 540, Quantity = 12},
                new Product { Id =258, Name = "Loquat", ScientificName = "Loquat", Category = "Fru", Price = 980, Quantity = 66},
                new Product { Id =259, Name = "Longan", ScientificName = "Longan", Category = "Fru", Price = 15, Quantity = 21},
                new Product { Id =260, Name = "Lychee", ScientificName = "Lychee", Category = "Fru", Price = 358, Quantity = 27},
                new Product { Id =261, Name = "Mango", ScientificName = "Mango", Category = "Fru", Price = 154, Quantity = 11},
                new Product { Id =262, Name = "Marionberry", ScientificName = "Marionberry", Category = "Fru", Price = 56, Quantity = 63},
                new Product { Id =263, Name = "Melon", ScientificName = "Melon", Category = "Fru", Price = 999, Quantity = 88},
                new Product { Id =264, Name = "Cantaloupe", ScientificName = "Cantaloupe", Category = "Fru", Price = 115, Quantity = 59},
                new Product { Id =265, Name = "Honeydew", ScientificName = "Honeydew", Category = "Fru", Price = 625, Quantity = 57},
                new Product { Id =266, Name = "Watermelon", ScientificName = "Watermelon", Category = "Fru", Price = 986, Quantity = 82},
                new Product { Id =267, Name = "Miracle fruit", ScientificName = "Miracle fruit", Category = "Fru", Price = 690, Quantity = 27},
                new Product { Id =268, Name = "Mulberry", ScientificName = "Mulberry", Category = "Fru", Price = 177, Quantity = 62},
                new Product { Id =269, Name = "Nectarine", ScientificName = "Nectarine", Category = "Fru", Price = 411, Quantity = 41},
                new Product { Id =270, Name = "Nance", ScientificName = "Nance", Category = "Fru", Price = 162, Quantity = 31},
                new Product { Id =271, Name = "Olive", ScientificName = "Olive", Category = "Fru", Price = 91, Quantity = 48},
                new Product { Id =272, Name = "Orange", ScientificName = "Orange", Category = "Fru", Price = 209, Quantity = 57},
                new Product { Id =273, Name = "Blood orange", ScientificName = "Blood orange", Category = "Fru", Price = 117, Quantity = 65},
                new Product { Id =274, Name = "Clementine", ScientificName = "Clementine", Category = "Fru", Price = 995, Quantity = 71},
                new Product { Id =275, Name = "Mandarine", ScientificName = "Mandarine", Category = "Fru", Price = 245, Quantity = 100},
                new Product { Id =276, Name = "Tangerine", ScientificName = "Tangerine", Category = "Fru", Price = 927, Quantity = 66},
                new Product { Id =277, Name = "Papaya", ScientificName = "Papaya", Category = "Fru", Price = 820, Quantity = 85},
                new Product { Id =278, Name = "Passionfruit", ScientificName = "Passionfruit", Category = "Fru", Price = 356, Quantity = 77},
                new Product { Id =279, Name = "Peach", ScientificName = "Peach", Category = "Fru", Price = 588, Quantity = 23},
                new Product { Id =280, Name = "Pear", ScientificName = "Pear", Category = "Fru", Price = 303, Quantity = 36},
                new Product { Id =281, Name = "Persimmon", ScientificName = "Persimmon", Category = "Fru", Price = 872, Quantity = 96},
                new Product { Id =282, Name = "Physalis", ScientificName = "Physalis", Category = "Fru", Price = 849, Quantity = 24},
                new Product { Id =283, Name = "Plantain", ScientificName = "Plantain", Category = "Fru", Price = 43, Quantity = 64},
                new Product { Id =284, Name = "Plum", ScientificName = "Plum", Category = "Fru", Price = 557, Quantity = 28},
                new Product { Id =285, Name = "Prune (dried plum)", ScientificName = "Prune (dried plum)", Category = "Fru", Price = 838, Quantity = 51},
                new Product { Id =286, Name = "Pineapple", ScientificName = "Pineapple", Category = "Fru", Price = 49, Quantity = 56},
                new Product { Id =287, Name = "Plumcot (or Pluot)", ScientificName = "Plumcot (or Pluot)", Category = "Fru", Price = 631, Quantity = 59},
                new Product { Id =288, Name = "Pomegranate", ScientificName = "Pomegranate", Category = "Fru", Price = 875, Quantity = 48},
                new Product { Id =289, Name = "Pomelo", ScientificName = "Pomelo", Category = "Fru", Price = 707, Quantity = 16},
                new Product { Id =290, Name = "Purple mangosteen", ScientificName = "Purple mangosteen", Category = "Fru", Price = 905, Quantity = 76},
                new Product { Id =291, Name = "Quince", ScientificName = "Quince", Category = "Fru", Price = 571, Quantity = 93},
                new Product { Id =292, Name = "Raspberry", ScientificName = "Raspberry", Category = "Fru", Price = 820, Quantity = 74},
                new Product { Id =293, Name = "Salmonberry", ScientificName = "Salmonberry", Category = "Fru", Price = 75, Quantity = 27},
                new Product { Id =294, Name = "Rambutan", ScientificName = "Rambutan", Category = "Fru", Price = 329, Quantity = 20},
                new Product { Id =295, Name = "Redcurrant", ScientificName = "Redcurrant", Category = "Fru", Price = 314, Quantity = 12},
                new Product { Id =296, Name = "Salal berry", ScientificName = "Salal berry", Category = "Fru", Price = 780, Quantity = 36},
                new Product { Id =297, Name = "Salak", ScientificName = "Salak", Category = "Fru", Price = 701, Quantity = 95},
                new Product { Id =298, Name = "Satsuma", ScientificName = "Satsuma", Category = "Fru", Price = 94, Quantity = 47},
                new Product { Id =299, Name = "Star fruit", ScientificName = "Star fruit", Category = "Fru", Price = 833, Quantity = 70},
                new Product { Id =300, Name = "Strawberry", ScientificName = "Strawberry", Category = "Fru", Price = 938, Quantity = 34},
                new Product { Id =301, Name = "Tamarillo", ScientificName = "Tamarillo", Category = "Fru", Price = 49, Quantity = 43},
                new Product { Id =302, Name = "Tamarind", ScientificName = "Tamarind", Category = "Fru", Price = 854, Quantity = 67},
                new Product { Id =303, Name = "Tomato", ScientificName = "Tomato", Category = "Fru", Price = 971, Quantity = 63},
                new Product { Id =304, Name = "Ugli fruit", ScientificName = "Ugli fruit", Category = "Fru", Price = 426, Quantity = 23},
                new Product { Id =305, Name = "Yuzu", ScientificName = "Yuzu", Category = "Fru", Price = 56, Quantity = 85},
                new Product { Id =306, Name = "Beaten rice - Rice Flakes", ScientificName = "Beaten rice - Rice Flakes", Category = "Gra", Price = 24, Quantity = 46},
                new Product { Id =307, Name = "Poha", ScientificName = "Poha", Category = "Gra", Price = 413, Quantity = 20},
                new Product { Id =308, Name = "Pohe", ScientificName = "Pohe", Category = "Gra", Price = 286, Quantity = 11},
                new Product { Id =309, Name = "Avalakki", ScientificName = "Avalakki", Category = "Gra", Price = 396, Quantity = 13},
                new Product { Id =310, Name = "Bengal Gram", ScientificName = "Bengal Gram", Category = "Gra", Price = 54, Quantity = 19},
                new Product { Id =311, Name = "Chana", ScientificName = "Chana", Category = "Gra", Price = 27, Quantity = 100},
                new Product { Id =312, Name = "Harabhara - Chana", ScientificName = "Harabhara - Chana", Category = "Gra", Price = 165, Quantity = 15},
                new Product { Id =313, Name = "Kadale", ScientificName = "Kadale", Category = "Gra", Price = 78, Quantity = 59},
                new Product { Id =314, Name = "Black Gram Whole", ScientificName = "Black Gram Whole", Category = "Gra", Price = 434, Quantity = 38},
                new Product { Id =315, Name = "Urad Dal - Kaali Dal Sabut", ScientificName = "Urad Dal - Kaali Dal Sabut", Category = "Gra", Price = 178, Quantity = 84},
                new Product { Id =316, Name = "Udid akkhe", ScientificName = "Udid akkhe", Category = "Gra", Price = 327, Quantity = 65},
                new Product { Id =317, Name = "Uddu", ScientificName = "Uddu", Category = "Gra", Price = 64, Quantity = 51},
                new Product { Id =318, Name = "Black Eyed Beans", ScientificName = "Black Eyed Beans", Category = "Gra", Price = 532, Quantity = 50},
                new Product { Id =319, Name = "Chawli - Lobhia", ScientificName = "Chawli - Lobhia", Category = "Gra", Price = 516, Quantity = 77},
                new Product { Id =320, Name = "Chavali", ScientificName = "Chavali", Category = "Gra", Price = 857, Quantity = 50},
                new Product { Id =321, Name = "Alasande Kalu", ScientificName = "Alasande Kalu", Category = "Gra", Price = 407, Quantity = 40},
                new Product { Id =322, Name = "Broken Wheat", ScientificName = "Broken Wheat", Category = "Gra", Price = 632, Quantity = 35},
                new Product { Id =323, Name = "Dalia", ScientificName = "Dalia", Category = "Gra", Price = 432, Quantity = 19},
                new Product { Id =324, Name = "Dalia", ScientificName = "Dalia", Category = "Gra", Price = 170, Quantity = 64},
                new Product { Id =325, Name = "Godi Rave", ScientificName = "Godi Rave", Category = "Gra", Price = 350, Quantity = 11},
                new Product { Id =326, Name = "Chickpeas (brown)", ScientificName = "Chickpeas (brown)", Category = "Gra", Price = 285, Quantity = 11},
                new Product { Id =327, Name = "Chana", ScientificName = "Chana", Category = "Gra", Price = 471, Quantity = 85},
                new Product { Id =328, Name = "Harabhara - Chana", ScientificName = "Harabhara - Chana", Category = "Gra", Price = 424, Quantity = 44},
                new Product { Id =329, Name = "Kadale", ScientificName = "Kadale", Category = "Gra", Price = 415, Quantity = 27},
                new Product { Id =330, Name = "Chickpeas (green)", ScientificName = "Chickpeas (green)", Category = "Gra", Price = 717, Quantity = 83},
                new Product { Id =331, Name = "Cholia - Hara Chana", ScientificName = "Cholia - Hara Chana", Category = "Gra", Price = 670, Quantity = 28},
                new Product { Id =332, Name = "Harabhara - Hirave Chane", ScientificName = "Harabhara - Hirave Chane", Category = "Gra", Price = 105, Quantity = 37},
                new Product { Id =333, Name = "kadale", ScientificName = "kadale", Category = "Gra", Price = 89, Quantity = 66},
                new Product { Id =334, Name = "Chickpeas (white)", ScientificName = "Chickpeas (white)", Category = "Gra", Price = 267, Quantity = 84},
                new Product { Id =335, Name = "Kabuli Chana", ScientificName = "Kabuli Chana", Category = "Gra", Price = 24, Quantity = 71},
                new Product { Id =336, Name = "Kabuli Chane", ScientificName = "Kabuli Chane", Category = "Gra", Price = 140, Quantity = 84},
                new Product { Id =337, Name = "Kabul Kadale", ScientificName = "Kabul Kadale", Category = "Gra", Price = 947, Quantity = 53},
                new Product { Id =338, Name = "Corn", ScientificName = "Corn", Category = "Gra", Price = 604, Quantity = 19},
                new Product { Id =339, Name = "Makai - Makki", ScientificName = "Makai - Makki", Category = "Gra", Price = 975, Quantity = 32},
                new Product { Id =340, Name = "Maka", ScientificName = "Maka", Category = "Gra", Price = 639, Quantity = 52},
                new Product { Id =341, Name = "Muskina Jola", ScientificName = "Muskina Jola", Category = "Gra", Price = 548, Quantity = 18},
                new Product { Id =342, Name = "Green Gram", ScientificName = "Green Gram", Category = "Gra", Price = 258, Quantity = 39},
                new Product { Id =343, Name = "Moong", ScientificName = "Moong", Category = "Gra", Price = 681, Quantity = 53},
                new Product { Id =344, Name = "Moog - Akkhe", ScientificName = "Moog - Akkhe", Category = "Gra", Price = 872, Quantity = 94},
                new Product { Id =345, Name = "Hesar Kalu", ScientificName = "Hesar Kalu", Category = "Gra", Price = 665, Quantity = 75},
                new Product { Id =346, Name = "Finger Millet", ScientificName = "Finger Millet", Category = "Gra", Price = 179, Quantity = 16},
                new Product { Id =347, Name = "Sattu", ScientificName = "Sattu", Category = "Gra", Price = 198, Quantity = 91},
                new Product { Id =348, Name = "Nachani", ScientificName = "Nachani", Category = "Gra", Price = 167, Quantity = 62},
                new Product { Id =349, Name = "Ragi", ScientificName = "Ragi", Category = "Gra", Price = 501, Quantity = 61},
                new Product { Id =350, Name = "Horse Bean", ScientificName = "Horse Bean", Category = "Gra", Price = 577, Quantity = 31},
                new Product { Id =351, Name = "Urad", ScientificName = "Urad", Category = "Gra", Price = 888, Quantity = 33},
                new Product { Id =352, Name = "Udid", ScientificName = "Udid", Category = "Gra", Price = 416, Quantity = 49},
                new Product { Id =353, Name = "Uddu", ScientificName = "Uddu", Category = "Gra", Price = 881, Quantity = 32},
                new Product { Id =354, Name = "Horse Gram - Horse Grain", ScientificName = "Horse Gram - Horse Grain", Category = "Gra", Price = 182, Quantity = 46},
                new Product { Id =355, Name = "Kulthi", ScientificName = "Kulthi", Category = "Gra", Price = 204, Quantity = 96},
                new Product { Id =356, Name = "Kulith", ScientificName = "Kulith", Category = "Gra", Price = 220, Quantity = 46},
                new Product { Id =357, Name = "hurali kalu)", ScientificName = "hurali kalu)", Category = "Gra", Price = 456, Quantity = 12},
                new Product { Id =358, Name = "Millet - Sorghum", ScientificName = "Millet - Sorghum", Category = "Gra", Price = 473, Quantity = 43},
                new Product { Id =359, Name = "Jowar", ScientificName = "Jowar", Category = "Gra", Price = 673, Quantity = 38},
                new Product { Id =360, Name = "Jwari", ScientificName = "Jwari", Category = "Gra", Price = 734, Quantity = 86},
                new Product { Id =361, Name = "Jola", ScientificName = "Jola", Category = "Gra", Price = 627, Quantity = 79},
                new Product { Id =362, Name = "Pearl Millet", ScientificName = "Pearl Millet", Category = "Gra", Price = 189, Quantity = 88},
                new Product { Id =363, Name = "Bajra", ScientificName = "Bajra", Category = "Gra", Price = 482, Quantity = 93},
                new Product { Id =364, Name = "Bajri", ScientificName = "Bajri", Category = "Gra", Price = 406, Quantity = 53},
                new Product { Id =365, Name = "Sajje - sajji", ScientificName = "Sajje - sajji", Category = "Gra", Price = 803, Quantity = 89},
                new Product { Id =366, Name = "Puffed Rice", ScientificName = "Puffed Rice", Category = "Gra", Price = 105, Quantity = 82},
                new Product { Id =367, Name = "Kurmura", ScientificName = "Kurmura", Category = "Gra", Price = 944, Quantity = 29},
                new Product { Id =368, Name = "Churmure", ScientificName = "Churmure", Category = "Gra", Price = 874, Quantity = 91},
                new Product { Id =369, Name = "Puri - Kadale Puri", ScientificName = "Puri - Kadale Puri", Category = "Gra", Price = 394, Quantity = 27},
                new Product { Id =370, Name = "Quinoa - available in south american countries", ScientificName = "Quinoa - available in south american countries", Category = "Gra", Price = 427, Quantity = 98},
                new Product { Id =371, Name = "Red Kidney Beans", ScientificName = "Red Kidney Beans", Category = "Gra", Price = 757, Quantity = 95},
                new Product { Id =372, Name = "Rajma", ScientificName = "Rajma", Category = "Gra", Price = 578, Quantity = 90},
                new Product { Id =373, Name = "Rajma", ScientificName = "Rajma", Category = "Gra", Price = 681, Quantity = 48},
                new Product { Id =374, Name = "Rajma", ScientificName = "Rajma", Category = "Gra", Price = 996, Quantity = 57},
                new Product { Id =375, Name = "Red Lentil", ScientificName = "Red Lentil", Category = "Gra", Price = 193, Quantity = 19},
                new Product { Id =376, Name = "Masoor", ScientificName = "Masoor", Category = "Gra", Price = 387, Quantity = 75},
                new Product { Id =377, Name = "Masoor", ScientificName = "Masoor", Category = "Gra", Price = 258, Quantity = 70},
                new Product { Id =378, Name = "Masoor", ScientificName = "Masoor", Category = "Gra", Price = 338, Quantity = 80},
                new Product { Id =379, Name = "Rice", ScientificName = "Rice", Category = "Gra", Price = 30, Quantity = 88},
                new Product { Id =380, Name = "Chaval", ScientificName = "Chaval", Category = "Gra", Price = 698, Quantity = 94},
                new Product { Id =381, Name = "Tandul", ScientificName = "Tandul", Category = "Gra", Price = 429, Quantity = 32},
                new Product { Id =382, Name = "Akki", ScientificName = "Akki", Category = "Gra", Price = 648, Quantity = 33},
                new Product { Id =383, Name = "Rice (Parboiled)", ScientificName = "Rice (Parboiled)", Category = "Gra", Price = 513, Quantity = 100},
                new Product { Id =384, Name = "Ukda Tandul", ScientificName = "Ukda Tandul", Category = "Gra", Price = 20, Quantity = 52},
                new Product { Id =385, Name = "Kudupul Akki", ScientificName = "Kudupul Akki", Category = "Gra", Price = 633, Quantity = 88},
                new Product { Id =386, Name = "Semolina - Cream of Wheat", ScientificName = "Semolina - Cream of Wheat", Category = "Gra", Price = 441, Quantity = 26},
                new Product { Id =387, Name = "Rava - Suji - Sooji", ScientificName = "Rava - Suji - Sooji", Category = "Gra", Price = 266, Quantity = 44},
                new Product { Id =388, Name = "Rava", ScientificName = "Rava", Category = "Gra", Price = 716, Quantity = 84},
                new Product { Id =389, Name = "Rave", ScientificName = "Rave", Category = "Gra", Price = 610, Quantity = 57},
                new Product { Id =390, Name = "Split Chickpeas - Split Bengal Gram", ScientificName = "Split Chickpeas - Split Bengal Gram", Category = "Gra", Price = 106, Quantity = 41},
                new Product { Id =391, Name = "Chana Dal", ScientificName = "Chana Dal", Category = "Gra", Price = 362, Quantity = 75},
                new Product { Id =392, Name = "Chanyachi Dal, Harbhara dal", ScientificName = "Chanyachi Dal, Harbhara dal", Category = "Gra", Price = 428, Quantity = 82},
                new Product { Id =393, Name = "Kadale Bele", ScientificName = "Kadale Bele", Category = "Gra", Price = 834, Quantity = 92},
                new Product { Id =394, Name = "Split Black Gram", ScientificName = "Split Black Gram", Category = "Gra", Price = 409, Quantity = 42},
                new Product { Id =395, Name = "Urad Dal - Kaali Dal", ScientificName = "Urad Dal - Kaali Dal", Category = "Gra", Price = 625, Quantity = 11},
                new Product { Id =396, Name = "Udid Dal", ScientificName = "Udid Dal", Category = "Gra", Price = 277, Quantity = 14},
                new Product { Id =397, Name = "Uddina Bele", ScientificName = "Uddina Bele", Category = "Gra", Price = 550, Quantity = 20},
                new Product { Id =398, Name = "Split Green Gram", ScientificName = "Split Green Gram", Category = "Gra", Price = 146, Quantity = 70},
                new Product { Id =399, Name = "Moong Dal", ScientificName = "Moong Dal", Category = "Gra", Price = 690, Quantity = 32},
                new Product { Id =400, Name = "Moog dal - Mugachi dal", ScientificName = "Moog dal - Mugachi dal", Category = "Gra", Price = 92, Quantity = 60},
                new Product { Id =401, Name = "Hesaru Bele", ScientificName = "Hesaru Bele", Category = "Gra", Price = 749, Quantity = 58},
                new Product { Id =402, Name = "Split Red Gram", ScientificName = "Split Red Gram", Category = "Gra", Price = 361, Quantity = 89},
                new Product { Id =403, Name = "Tuvar Dal - Arhar Dal", ScientificName = "Tuvar Dal - Arhar Dal", Category = "Gra", Price = 194, Quantity = 92},
                new Product { Id =404, Name = "Toor dal - Turichi dal", ScientificName = "Toor dal - Turichi dal", Category = "Gra", Price = 646, Quantity = 68},
                new Product { Id =405, Name = "Tugri Bele", ScientificName = "Tugri Bele", Category = "Gra", Price = 431, Quantity = 86},
                new Product { Id =406, Name = "Split Red Lentil", ScientificName = "Split Red Lentil", Category = "Gra", Price = 746, Quantity = 23},
                new Product { Id =407, Name = "Masoor Dal", ScientificName = "Masoor Dal", Category = "Gra", Price = 519, Quantity = 49},
                new Product { Id =408, Name = "Masoor Dal", ScientificName = "Masoor Dal", Category = "Gra", Price = 64, Quantity = 46},
                new Product { Id =409, Name = "Masoor Bele", ScientificName = "Masoor Bele", Category = "Gra", Price = 656, Quantity = 71},
                new Product { Id =410, Name = "Wheat", ScientificName = "Wheat", Category = "Gra", Price = 50, Quantity = 84},
                new Product { Id =411, Name = "Gehun", ScientificName = "Gehun", Category = "Gra", Price = 809, Quantity = 16},
                new Product { Id =412, Name = "Gahu", ScientificName = "Gahu", Category = "Gra", Price = 905, Quantity = 63},
                new Product { Id =413, Name = "Godi", ScientificName = "Godi", Category = "Gra", Price = 103, Quantity = 35}

        };
        #endregion

        public IEnumerable<Product> GetAllProducts()
        {
            return products;
        }

        public IHttpActionResult GetProduct(int id)
        {
            var product = products.FirstOrDefault((p) => p.Id == id);
            if (product == null)
            {
                return NotFound();
            }
            return Ok(product);
        }
    }
}